services:
  mh_clima_db:
    image: mysql:8.4.3
    container_name: mh_bot_clima_db
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - mh_bot_clima_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASS}"]
      interval: 5s
      timeout: 5s
      retries: 10

  mh_clima_web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: mh_bot_clima_web
    ports:
      - "8080:80"
    volumes:
      # Conectamos SOLO la carpeta src hacia el directorio público de Apache
      - ./src:/var/www/html
    depends_on:
      mh_clima_db:
        condition: service_healthy
    env_file:
      - .env

volumes:
  mh_bot_clima_data: